from django.urls import path
from . import views 
urlpatterns = [
    path('all-categories', views.allCategories, name='all-categories'),
    path('create-category', views.createCategory, name='create-category'),
    path('show-edit-category/<int:category_id>', views.showEditCategory, name='show-edit-category'),
    path('delete-category/<int:category_id>', views.deleteCategory, name='delete-category'),
    path('edit-category', views.editCategory, name='edit-category'),
    path('all-booklets/<int:user_id>', views.allBooklets, name='all-booklets'),
    path('create-booklet', views.createBooklet, name='create-booklet'),
    path('all-chapters/<int:booklet_id>', views.allChapters, name='all-chapters'),
    path('show-create-chapter/<int:booklet_id>', views.showCreateChapter, name='show-create-chapter'),
    path('create-chapter', views.createChapter, name='create-chapter'),
    path('all-pages/<int:booklet_id>/<int:chapter_id>', views.allPages, name='all-pages'),
    path('show-create-page/<int:chapter_id>', views.showCreatePage, name='show-create-page'),
    path('create-page', views.createPage, name='create-page'),
    path('show-edit-booklet/<int:booklet_id>', views.showEditBooklet, name='show-edit-booklet'),
    path('edit-booklet', views.editBooklet, name='edit-booklet'),
    path('show-edit-chapter/<int:chapter_id>', views.showEditChapter, name='show-edit-chapter'),
    path('edit-chapter', views.editChapter, name='edit-chapter'),
    path('show-edit-page/<int:page_id>', views.showEditPage, name='show-edit-page'),
    path('edit-page', views.editPage, name='edit-page'),
    path('delete-booklet/<int:booklet_id>', views.deleteBooklet, name='delete-booklet'),
    path('delete-chapter/<int:chapter_id>', views.deleteChapter, name='delete-chapter'),
    path('delete-page/<int:page_id>', views.deletePage, name='delete-page'),
    path('show-book-cover/<int:booklet_id>', views.showBookCover, name='show-book-cover'),
    path('load-page-in-reader/<int:booklet_id>/<int:page_no>', views.loadPageInReader, name='load-page-in-reader'),
    path('load-chapterwise-page-in-reader/<int:page_id>/<int:page_no>', views.loadChapterwisePageInReader, name='load-chapterwise-page-in-reader'),
    path('go-to-chapter/<int:booklet_id>/<int:chapter_no>', views.goToChapter, name='go-to-chapter'),
    path('publish-booklet/<int:booklet_id>', views.publishBooklet, name='publish-booklet'),
    path('rate-booklet', views.rateBooklet, name='rate-booklet')
]