# Generated by Django 5.1.5 on 2025-01-22 07:19

import booklets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tag_line', models.CharField(default=None, max_length=255, null=True)),
                ('cover_photo', models.ImageField(default=None, null=True, upload_to=booklets.models.save_cover_photo)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklets.booklet')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, null=True, upload_to=booklets.models.save_page_photo)),
                ('video_link', models.CharField(default=None, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklets.booklet')),
                ('chapter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booklets.chapter')),
            ],
        ),
    ]
