# Generated by Django 5.1.5 on 2025-01-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booklets.category'),
        ),
    ]
