# Generated by Django 5.1.5 on 2025-01-25 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0004_booklet_unique_title_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booklet',
            name='unique_title_constraint',
        ),
        migrations.AddConstraint(
            model_name='booklet',
            constraint=models.UniqueConstraint(fields=('title', 'user_id'), name='unique_title_constraint', violation_error_message='You have already created a booklet with similar name'),
        ),
    ]
