# Generated by Django 5.1.5 on 2025-01-26 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0005_remove_booklet_unique_title_constraint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booklet',
            name='unique_title_constraint',
        ),
        migrations.AlterField(
            model_name='page',
            name='video_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='booklet',
            constraint=models.UniqueConstraint(fields=('title', 'user_id'), name='unique_title_constraint'),
        ),
    ]
