# Generated by Django 5.1.5 on 2025-02-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0007_booklet_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='if_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booklet',
            name='publishing_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
