# Generated by Django 5.1.5 on 2025-02-04 08:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='/media/default.png', upload_to=accounts.models.save_profile_photo),
        ),
    ]
