# Generated by Django 5.1.5 on 2025-02-04 08:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default.png', upload_to=accounts.models.save_profile_photo),
        ),
    ]
